version: '3'
services:
  spigot:
    build: .
    container_name: spigot
    tmpfs:
      - /spigot
    volumes:
      - ./worlds/world:/spigot/world
      - ./configs/spigot.yml:/spigot/spigot.yml
      - ./configs/bukkit.yml:/spigot/bukkit.yml
      - ./configs/server.properties:/spigot/server.properties
      - ./plugins:/spigot/plugins
    network_mode: bridge
    ports:
      - 25565:25565/tcp
      - 5005:5005/tcp
    environment:
      - ACCEPT_EULA=true
      - SPIGOT_VERSION=1.19.2
    restart: always
